name: "🐛 Bug Report"
description: Ops, sorry about that 😅
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        <h3>Thanks for reporting an issue!</h3>

        Before starting to fill in the form, I have already made sure that:

        - I've already verified that it's a bug related to the profile readme generator and not related to some external resource the app uses;
        - I already checked to see if there is already an issue related to my problem;

  - type: textarea
    id: bug-description
    attributes:
      label: What happens?
      description: A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Additional information about your environment
      value: |
        - **Device**: [e.g. iphoneX, desktop]
        - **OS**: [e.g. ios, windows]
        - **Browser**: [e.g. opera, chrome]
        - **Version**: [e.g. 22]
    validations:
      required: true

  - type: textarea
    id: bug-context
    attributes:
      label: Additional context
      description: Add any other context you can provide about the problem here.
