blank_issues_enabled: false
contact_links:
  - name: ❤ Support
    url: https://www.paypal.com/donate/?hosted_button_id=FR3A2DGVYKGJS
    about: Loved the tool? Please consider donating 💸 to help it improve!
